# Generated by Django 4.2.5 on 2023-09-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.TextField()),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='Chef/')),
            ],
        ),
    ]
